### ISSUE TITLE
way.js doesn't work in Safari 7.0.6

### ISSUE THREAD

**Issue by akashivskyy** [gwendall/way.js#20]
Demos don't seem to be working in Safari 7, is it a known issue?

![zrzut ekranu 2014-08-20 o 22 47 45](https://cloud.githubusercontent.com/assets/565231/3988072/5291c3b6-28ac-11e4-840a-0c5eb127a47e.png)

``` none
[Error] TypeError: 'undefined' is not a function (evaluating 'parent.matches(selector)')
    parent (way.js, line 1523)
    registerRepeats (way.js, line 417)
    registerDependencies (way.js, line 526)
    eventInit (way.js, line 1634)
    onreadystatechange (way.js, line 1556)
[Error] TypeError: 'undefined' is not a function (evaluating 'parent.matches(selector)')
    parent (way.js, line 1523)
    registerRepeats (way.js, line 417)
    registerDependencies (way.js, line 526)
    (anonymous function) (way.js, line 1607)
```

Works in Chrome 36, though:

![zrzut ekranu 2014-08-20 o 22 48 24](https://cloud.githubusercontent.com/assets/565231/3988083/6f07acb8-28ac-11e4-9cc0-0322b875058e.png)
